server:
  port: 41101
  tag: cloud-eureka-client-tag

spring:
  application:
    name: cloud-eureka-client
  # Spring Cloud Ribbon 处于维护阶段，可以配置为 false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 多个注册中心用逗号分隔，server 使用了安全时 http://user:password@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        # "*" 表示包含所有 ["health","info","metrics","prometheus"]
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      show-details: ALWAYS

# actuator 自定义 info 信息
info:
  app:
    name: cloud-eureka-client
    description: Eureka Client Application
    version: 1.0.0

logging:
  level:
    root: info
    com.netflix.discovery: debug
