spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${db.driverClassName}
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    druid:
      url: ${db.url}
      driver-class-name: ${db.driverClassName}
      username: ${db.user}
      password: ${db.password}
      initial-size: 8
      max-active: 32
      min-idle: 8
      max-wait: 60000
      validation-query-timeout: 60000
      min-evictable-idle-time-millis: 100000
      time-between-eviction-runs-millis: 60000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      validation-query: 'SELECT now()'
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
