server:
  port: 31010

spring:
  application:
    name: CloudOpenfeign

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    # 需要 actuator 依赖支持，EurekaDiscoveryClientConfiguration
    healthcheck:
      enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# When Hystrix is enabled, its timeout configuration defaults to 1000 milliseconds.
# org.springframework.cloud.openfeign.FeignAutoConfiguration
# openfeign
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    # feign 最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 32
    connection-timeout: 3000
  circuitbreaker:
    enabled: true
  client:
    config:
      # 全局默认的配置参数 FeignClientProperties
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      # 针对具体的 client 定制参数
      CloudEurekaClient:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: ["info", "health"]

# /actuator/info
info:
  application: ${spring.application.name}
  port: ${server.port}

logging:
  level:
    com.netflix.discovery: info
    org.apache.http: info
    com.netflix.loadbalancer: info
