server:
  port: 49000

unify:
  exception:
    # 发生异常时是否推送错误堆栈信息
    debug: true

spring:
  redis:
    # 111.231.92.115
    host: 127.0.0.1
    port: 6379
    database: 12
    password: redis
    timeout: 3000
    lettuce:
      pool:
        # Lettuce
        # 连接池最大连接数（使用负值表示没有限制） (CPU cores + 1)
        max-active: 5
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
      # 关闭超时时间
      shutdown-timeout: 100
