server:
  port: 30020
spring:
  rabbitmq:
    host: 10.0.41.80
    port: 5672
    username: rabbitmq
    password: rabbitmq
    publisherConfirmType: CORRELATED
    # 确认消息已发送到队列(Queue)
    publisherReturns: true