eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 2
#    status-page-url-path: ${server.servletPath}/info
#    health-check-url-path: ${server.servletPath}/health

spring:
  application:
    name: spring-cloud-service-provider
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
logging:
  level:
    org.springframework.web: DEBUG
    cn.nihility.cloud.service: DEBUG
#  pattern:
#    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"

server:
  port: 52200
#  tomcat:
#    max-threads: 10


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS