server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    # true - 使用 ip 地址
    preferIpAddress: false
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 5
    # 多长时间没收到心跳后可以移除服务实例的时间
    leaseExpirationDurationInSeconds: 10
  server:
    # 自我保护 https://github.com/Netflix/eureka/wiki/Server-Self-Preservation-Mode
    enableSelfPreservation: false
    # 剔除服务间隔，单位毫秒
    evictionIntervalTimerInMs: 5000
  client:
    # 作为 eureka 服务端时，不需要把自己注册到 eureka server 给其它服务发现
    registerWithEureka: false
    # 是否拉取 eureka server 上注册的服务信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 需要 actuator 支持
    healthcheck:
      enabled: true