spring:
  application:
    name: CloudEurekaServer
  profiles:
    # single, v1, v2, v3
    active: single

management:
  endpoints:
    web:
      exposure:
        include: ["info", "health", "eureka"]