server:
  port: 30030

frofile:
  value: Inner Jar application.yml value

#spring:
#  profiles:
#    active: pro

property:
  propertyName: property姓名
  property-age: 20

another:
  propertyName: anotherProperty姓名
  property-age: 18

binder:
  list:
    - a
    - b
    - c
  map:
    key1: value1
    key2: value2
    key3: value3

logging:
  level:
    org.apache.http.impl.conn.PoolingHttpClientConnectionManager: info