server:
  port: 8761

spring:
  # Spring Cloud Ribbon 处于维护阶段
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: 'admin'
      password: 'admin'

eureka:
  instance:
    hostname: localhost
    # 是否优先使用 ip 来作为主机名, 负责发现获取的 host 就为 IP 地址，不是 host (注册的名称)
    preferIpAddress: false
    # client 多少秒发送心跳去注册中心续约
    leaseRenewalIntervalInSeconds: 30
    # server 等待 client 多少秒不去续约认为服务失效
    leaseExpirationDurationInSeconds: 90
    # 使用 security 安全
#    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}
  client:
    # 注册成功后是否定期检查服务健康状况
    healthcheck:
      enabled: true
    # 是否从 eureka server 获取注册的服务列表, 单体 Server 本身不用注册
    fetchRegistry: false
    # eureka 是否自己注册到 server 端，单体 server 可以不用注册
    registerWithEureka: false
    serviceUrl:
      # 默认的 url : http://localhost:8761/eureka/，配置了安全时 http://user:password@127.0.0.1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        # "*" 表示包含所有 ["health","info","metrics","prometheus"]
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
    com.netflix.discovery: debug
