spring:
  application:
    name: spring-cloud-hystrix-turbine
server:
  port: 52202

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

turbine:
  # 要监控的服务列表
  app-config: cloud-load-balancer-client,spring-cloud-service-provider
  cluster-name-expression: "'default'"