server:
  port: 30010

api:
  unify:
    exception:
      debugStackTrace: false

auth:
  authLoginPrefix: /auth/login
  ssoHost: http://10.0.41.80:30010

spring:
#  jackson:
     # 空值字段不返回
#    defaultPropertyInclusion: NON_EMPTY
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis
    # ms（毫秒）
    timeout: 3000
    # 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接，默认 8
        max-idle: 8
        # 连接池中的最小空闲连接，默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1

logging:
  level:
    org.redisson.command: info
    org.apache.http.impl.conn.PoolingHttpClientConnectionManager: info
    org.thymeleaf.TemplateEngine.CONFIG: info
